### ISSUE TITLE
每个metric的值不一定都是数字，希望可以处理其他情况。

### ISSUE THREAD

**Issue by qwzhou89** [MicroOps-cn/data_exporter#2]
比如
{"jsonrpc":"2.0","id":1,"result":"0xd8ef11"}
这种json数据，想把result的值提取出来保存现在用的[strconv.ParseFloat(val, 64)](https://github.com/MicroOps-cn/data_exporter/blob/ffe4435d8128f8dcf394eaaa0450f9a69b170e72/collector/metric.go#L256)会报错误。

我看json_exporter的实现
https://github.com/prometheus-community/json_exporter/blob/c487740bb83f5b2a682d99161cbe8e4209ba4b2e/exporter/util.go#L41
可以参考做改造使用吧。

```go
func SanitizeValue(s string) (float64, error) {
	var err error
	var value float64
	var resultErr string

	if value, err = strconv.ParseFloat(s, 64); err == nil {
		return value, nil
	}
	resultErr = fmt.Sprintf("%s", err)

	if intValue, err := strconv.ParseInt(s, 0, 64); err == nil {
		return float64(intValue), nil
	}
	resultErr = resultErr + "; " + fmt.Sprintf("%s", err)

	if boolValue, err := strconv.ParseBool(s); err == nil {
		if boolValue {
			return 1.0, nil
		}
		return 0.0, nil
	}
	resultErr = resultErr + "; " + fmt.Sprintf("%s", err)

	if s == "<nil>" {
		return math.NaN(), nil
	}
	return value, fmt.Errorf(resultErr)
}
```

**Comment by MicroOps-cn** [comment]
谢谢你的建议，我晚点试试

**Comment by MicroOps-cn** [comment]
已实现你提的建议，可[查看文档](https://github.com/MicroOps-cn/data_exporter/blob/master/README.md#templexec)。

使用示例
https://github.com/MicroOps-cn/data_exporter/blob/a26746efe27144330c5137b5dc2736e57c82d4d1/examples/data_exporter.yaml#L23-L26
https://github.com/MicroOps-cn/data_exporter/blob/a26746efe27144330c5137b5dc2736e57c82d4d1/examples/my_data.json#L1-L17

**Comment by qwzhou89** [comment]
你的实现功能更强大啊，回头试试。

**Comment by MicroOps-cn** [comment]
> 你的实现功能更强大啊，回头试试。

只是为了方便扩展
