### ISSUE TITLE
Container not working

### ISSUE THREAD

**Issue by deepankersharmaa** [MicroOps-cn/data_exporter#5]
HI,

While using it as docker container. I have got the images from _"docker.io/microops/data_exporter"_.
but here when i try to run container using this command as you mentioned in this docker command: _"docker run --rm -d -p 9116:9116 --name data_exporter -v pwd:/etc/data_exporter/ microops/data_exporter:0.2.0 --config.path=/etc/data_exporter/config.yml"_ nothing will happened container will be in exited mode.

Can you please brief  which files i have to put in "/etc/data_exporter/"  and what has to be written in "config.path=/etc/data_exporter/config.yml"

Thanks for your support.

Regards,
Deepankar

**Comment by MicroOps-cn** [comment]
You can run a demo by executing the following command：
```
git clone https://github.com/MicroOps-cn/data_exporter
cd data_exporter/examples/
docker run  -p 9116:9116 -v data_exporter/examples/:/etc/data_exporter/ --name data_exporter microops/data_exporter:0.3.2 --config.path=/etc/data_exporter/data_exporter.yaml
docker logs data_exporter
```

**Comment by deepankersharmaa** [comment]
That great,

Thank you So much for you support.

Let me try it. will get back to you if needed any help.

Regards,
Deepankar

**Comment by MicroOps-cn** [comment]
Sorry, I made a mistake yesterday. You can change the "../example/" in "example/data_exporter.yaml" to "/etc/data_exporter/"

**Comment by MicroOps-cn** [comment]
The final results are as follows:
```
meas_info_fddl{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL08-123456-11"} 0
meas_info_fddl{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL08-123456-21"} 0
meas_info_fddl{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL08-123456-31"} 0
meas_info_fddl{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL21-123456-11"} 0
meas_info_fddl{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL21-123456-21"} 0
meas_info_fddl{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL21-123456-31"} 0
# HELP meas_info_rpc 
# TYPE meas_info_rpc gauge
meas_info_rpc{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL08-123456-11"} 0
meas_info_rpc{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL08-123456-21"} 0
meas_info_rpc{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL08-123456-31"} 0
meas_info_rpc{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL21-123456-11"} 0
meas_info_rpc{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL21-123456-21"} 0
meas_info_rpc{name="ENBFunction=ORAN-MET-TB,EUtranCellFDD=TL21-123456-31"} 0
```

**Comment by deepankersharmaa** [comment]
Hi,

Thanks for your support.

I have tried the way you mentioned. 
But as per my requirement we have to extract each counter values to metrics like mentioned in below attached image.
![image](https://user-images.githubusercontent.com/50438957/174588929-3e524e61-0859-4935-af11-61dc67070199.png)

Also, could you please suggest some way to how can i write metrics datapoints with respect below attached XML file.
[PM-Data.zip](https://github.com/MicroOps-cn/data_exporter/files/8940066/PM-Data.zip)
