### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by girisubhra** [MicroOps-cn/data_exporter#6]
I am facing issues while compiling
step-1 : make common-build
Success
Step-2 : make
Error:
# make
>> checking code style
gofmt checking failed!
diff -u ./pkg/tail@v1.0.0/tail_posix.go.orig ./pkg/tail@v1.0.0/tail_posix.go
--- ./pkg/tail@v1.0.0/tail_posix.go.orig        2022-06-28 22:00:04.209118589 +0900
+++ ./pkg/tail@v1.0.0/tail_posix.go     2022-06-28 22:00:04.209118589 +0900
@@ -1,3 +1,4 @@
+//go:build linux || darwin || freebsd || netbsd || openbsd
 // +build linux darwin freebsd netbsd openbsd

 package tail
diff -u ./pkg/tail@v1.0.0/tail_windows.go.orig ./pkg/tail@v1.0.0/tail_windows.go
--- ./pkg/tail@v1.0.0/tail_windows.go.orig      2022-06-28 22:00:04.208118589 +0900
+++ ./pkg/tail@v1.0.0/tail_windows.go   2022-06-28 22:00:04.208118589 +0900
@@ -1,3 +1,4 @@
+//go:build windows
 // +build windows

 package tail
diff -u ./pkg/tail@v1.0.0/winfile/winfile.go.orig ./pkg/tail@v1.0.0/winfile/winfile.go
--- ./pkg/tail@v1.0.0/winfile/winfile.go.orig   2022-06-28 22:00:04.208118589 +0900
+++ ./pkg/tail@v1.0.0/winfile/winfile.go        2022-06-28 22:00:04.208118589 +0900
@@ -1,3 +1,4 @@
+//go:build windows
 // +build windows

 package winfile

Please ensure you are using go version go1.18.3 linux/amd64 for formatting code.
make: *** [Makefile.common:132: common-style] Error 1

**Comment by MicroOps-cn** [comment]
The problem has been fixed and will be released in the next version. You can also directly pull the latest code for compilation. Thank you for your feedback



---Original---
From: "SUBHRA PRAKASH ***@***.***&gt;
Date: Tue, Jun 28, 2022 20:46 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MicroOps-cn/data_exporter] Compilation Error (Issue #6)




 
I am facing issues while compiling
 step-1 : make common-build
 Success
 Step-2 : make
 Error:
 
make
 
which: no yamllint in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/var/lib/snapd/snap/bin:/root/.go/bin:/root/go/bin)
   
checking code style
 ./main.go:125:24: expected expression
 ./pkg/wrapper/func.go:3:7: expected '(', found '['
 ./pkg/wrapper/slice.go:9:11: expected '(', found '['
 checking license header
 license header checking failed:
 ./collector/flags.go
 ./pkg/logs/logger.go
 ./pkg/logs/logs.go
 .***@***.***/ratelimiter/leakybucket.go
 .***@***.***/ratelimiter/leakybucket_test.go
 .***@***.***/ratelimiter/memory.go
 .***@***.***/ratelimiter/storage.go
 .***@***.***/tail_posix.go
 .***@***.***/tail_windows.go
 .***@***.***/watch/filechanges.go
 .***@***.***/winfile/winfile.go
 ./pkg/term/term.go
 ./pkg/term/term_unixlike.go
 ./pkg/term/term_windows.go
 ./pkg/wrapper/func.go
 ./pkg/wrapper/slice.go
 ./pkg/wrapper/slice_test.go
 make: *** [Makefile.common:142: common-check_license] Error 1
