### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by girisubhra** [MicroOps-cn/data_exporter#7]
step-1: make common-build
Success
Step-2: make
Error

 make
>> checking code style
>> checking license header
>> running golangci-lint
GO111MODULE=on go list -e -compiled -test=true -export=false -deps=true -find=false -tags= -- ./... > /dev/null
GO111MODULE=on /root/go/bin/golangci-lint run  ./...
pkg/logs/logs.go:81:18: undeclared name: `kingpin` (typecheck)
func AddFlags(a *kingpin.Application, config *Config) {
                 ^
pkg/logs/logs.go:23:2: "gopkg.in/alecthomas/kingpin.v2" imported but not used (typecheck)
        "gopkg.in/alecthomas/kingpin.v2"
        ^
main.go:125:24: expected expression (typecheck)
                metrics := wrapper.M[[]byte](ioutil.ReadAll(resp.Body))
                                     ^
collector/yaml.go:18:2: could not import encoding (-: could not load export data: cannot import "encoding" (unknown iexport format version 2), export data is newer version - update tool) (typecheck)
        "encoding"
        ^
collector/yaml.go:27:2: could not import unicode (-: could not load export data: cannot import "unicode" (unknown iexport format version 2), export data is newer version - update tool) (typecheck)
        "unicode"
        ^
collector/yaml.go:28:2: could not import unicode/utf8 (-: could not load export data: cannot import "unicode/utf8" (unknown iexport format version 2), export data is newer version - update tool) (typecheck)
        "unicode/utf8"
        ^
collector/collect.go:91:46: undeclared name: `yaml` (typecheck)
func (c *CollectConfig) UnmarshalYAML(value *yaml.Node) error {
                                             ^
collector/datasource.go:124:43: undeclared name: `yaml` (typecheck)
func (s *SendConfig) UnmarshalYAML(value *yaml.Node) error {
                                          ^
collector/datasource.go:140:44: undeclared name: `yaml` (typecheck)
func (s *SendConfigs) UnmarshalYAML(value *yaml.Node) error {
                                           ^
collector/flags.go:18:24: undeclared name: `kingpin` (typecheck)
func AddFlags(flagSet *kingpin.Application) {
                       ^
collector/labels.go:233:16: cfg.Regex.MatchString undefined (type Regexp has no field or method MatchString) (typecheck)
                if cfg.Regex.MatchString(val) {
                             ^
collector/labels.go:237:17: cfg.Regex.MatchString undefined (type Regexp has no field or method MatchString) (typecheck)
                if !cfg.Regex.MatchString(val) {
                              ^
collector/labels.go:247:24: cfg.Regex.FindStringSubmatchIndex undefined (type Regexp has no field or method FindStringSubmatchIndex) (typecheck)
                indexes := cfg.Regex.FindStringSubmatchIndex(val)
                                     ^
collector/labels.go:252:39: cfg.Regex.ExpandString undefined (type Regexp has no field or method ExpandString) (typecheck)
                target := model.LabelName(cfg.Regex.ExpandString([]byte{}, cfg.TargetLabel, val, indexes))
                                                    ^
collector/labels.go:257:20: cfg.Regex.ExpandString undefined (type Regexp has no field or method ExpandString) (typecheck)
                res := cfg.Regex.ExpandString([]byte{}, cfg.Replacement, val, indexes)
                                 ^
collector/labels.go:268:17: cfg.Regex.MatchString undefined (type Regexp has no field or method MatchString) (typecheck)
                        if cfg.Regex.MatchString(l.Name) {
                                     ^
collector/labels.go:269:22: cfg.Regex.ReplaceAllString undefined (type Regexp has no field or method ReplaceAllString) (typecheck)
                                res := cfg.Regex.ReplaceAllString(l.Name, cfg.Replacement)
                                                 ^
collector/labels.go:494:9: undeclared name: `xxhash` (typecheck)
                        h := xxhash.New()
                             ^
collector/labels.go:510:9: undeclared name: `xxhash` (typecheck)
        return xxhash.Sum64(b)
               ^
collector/labels.go:532:9: undeclared name: `xxhash` (typecheck)
        return xxhash.Sum64(b), b
               ^
collector/net.go:63:7: c.Close undefined (type *ConnReader has no field or method Close) (typecheck)
                                c.Close()
                                  ^
collector/net_test.go:53:13: conn.Close undefined (type connect has no field or method Close) (typecheck)
        defer conn.Close()
                   ^
collector/net_test.go:59:20: conn.Write undefined (type connect has no field or method Write) (typecheck)
                                _, err := conn.Write([]byte(fmt.Sprintf("%s\n", s)))
                                               ^
collector/collect.go:25:2: "gopkg.in/yaml.v3" imported but not used (typecheck)
        "gopkg.in/yaml.v3"
        ^
collector/datasource.go:25:2: "gopkg.in/yaml.v3" imported but not used (typecheck)
        "gopkg.in/yaml.v3"
        ^
collector/flags.go:16:8: "gopkg.in/alecthomas/kingpin.v2" imported but not used (typecheck)
import "gopkg.in/alecthomas/kingpin.v2"
       ^
collector/labels.go:21:2: "github.com/cespare/xxhash/v2" imported but not used (typecheck)
        "github.com/cespare/xxhash/v2"
        ^
collector/labels.go:23:2: "gopkg.in/yaml.v3" imported but not used (typecheck)
        "gopkg.in/yaml.v3"
        ^
collector/metric.go:27:2: "math" imported but not used (typecheck)
        "math"
        ^
config/config.go:91:5: sc.Lock undefined (type *SafeConfig has no field or method Lock) (typecheck)
        sc.Lock()
           ^
config/config.go:92:11: sc.Unlock undefined (type *SafeConfig has no field or method Unlock) (typecheck)
        defer sc.Unlock()
                 ^
config/config.go:98:5: sc.Lock undefined (type *SafeConfig has no field or method Lock) (typecheck)
        sc.Lock()
           ^
config/config.go:99:11: sc.Unlock undefined (type *SafeConfig has no field or method Unlock) (typecheck)
        defer sc.Unlock()
                 ^
config/config.go:103:5: sc.Lock undefined (type *SafeConfig has no field or method Lock) (typecheck)
        sc.Lock()
           ^
config/config.go:104:11: sc.Unlock undefined (type *SafeConfig has no field or method Unlock) (typecheck)
        defer sc.Unlock()
                 ^
pkg/wrapper/func.go:16:7: expected '(', found '[' (typecheck)
func M[T any](ret T, err error) T {
      ^
pkg/wrapper/slice.go:22:11: expected '(', found '[' (typecheck)
func Limit[T any](s []T, limit int, hidePosition int, manySuffix ...T) []T {
          ^
testings/testing.go:41:4: t.Log undefined (type *T has no field or method Log) (typecheck)
        t.Log(args...)
          ^
make: *** [Makefile.common:198: common-lint] Error 1

**Comment by MicroOps-cn** [comment]
It looks like your golangci lint version is too low,
- Execute /root/go/bin/golangci lint --version to see the results,
- Execute `curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2` or `go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2`
Try installing the latest version of golangci lint
-  Or compile directly without syntax checking: `make common-build && docker build -t data_exporter:0.4.1 .`

**Comment by girisubhra** [comment]
> It looks like your golangci lint version is too low,
> 
> * Execute `/root/go/bin/golangci-lint --version` to see the results,
> * Execute `curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.2` or `go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.46.2`
>   Try installing the latest version of golangci lint
> * Or compile directly without syntax checking: `make common-build && docker build -t data_exporter:0.4.1 .`

I installed latest version of golangci lint and executed make common-build && docker build -t data_exporter:0.4.1 .
Now it is successfully compiled.
