### ISSUE TITLE
How to extract data from multiple data files

### ISSUE THREAD

**Issue by girisubhra** [MicroOps-cn/data_exporter#9]
I have to read multiple data files. Please help how can i do that.
Example : There are pmdata1.xml, pmdata2.xml,pmdata3.xml in this location /data_exporter/tree/master/examples/xml_3gpp_ts
How it can be done

**Comment by MicroOps-cn** [comment]
like:
collects:   - name: "test-xml"     relabel_configs: [ ]     data_format: "json"     datasource:       - type: "file"         url: "/path/to/file1.xml"       - type: "file"         url: "/path/to/file2.xml"     metrics:        ........



---Original---
From: "SUBHRA PRAKASH ***@***.***&gt;
Date: Mon, Aug 22, 2022 19:05 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MicroOps-cn/data_exporter] How to extract data from multiple datafiles (Issue #9)




 
I have to read multiple data files. Please help how can i do that.
 Example : There are pmdata1.xml, pmdata2.xml,pmdata3.xml in this location /data_exporter/tree/master/examples/xml_3gpp_ts
 How it can be done

**Comment by MicroOps-cn** [comment]
collects:&nbsp;
&nbsp; - name: "test-xml"
&nbsp; &nbsp; &nbsp;data_format: "xml"&nbsp;
&nbsp; &nbsp; &nbsp;datasource:&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;- type: "file"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; url: "/path/to/file1.xml"&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp;- type: "file"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; url: "/path/to/file2.xml"&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;
&nbsp; &nbsp; &nbsp;metrics:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;........



---Original---
From: "SUBHRA PRAKASH ***@***.***&gt;
Date: Mon, Aug 22, 2022 19:05 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MicroOps-cn/data_exporter] How to extract data from multiple datafiles (Issue #9)




 
I have to read multiple data files. Please help how can i do that.
 Example : There are pmdata1.xml, pmdata2.xml,pmdata3.xml in this location /data_exporter/tree/master/examples/xml_3gpp_ts
 How it can be done
